import re
import yaml

from state import PipelineState, ACPMessage
from config import LLM_MODEL, LLM_TEMPERATURE, INTEREST_TOPICS, PROMPTS_DIR, OUTPUT_LANGUAGE_LABELS, SITE_URL
from llm import llm_client


def _extract_section(text: str, marker: str) -> str:
    pattern = rf"==={marker}===\s*(.*?)(?====[\w_]+=|$)"
    match = re.search(pattern, text, re.DOTALL)
    return match.group(1).strip() if match else ""


def _parse_seo_meta(raw_seo: str) -> dict:
    """Parse the ===SEO_META=== section into a structured dict."""
    meta = {}
    for line in raw_seo.splitlines():
        line = line.strip()
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if key in ("keywords", "internal_links"):
            # Strip surrounding brackets if present: [kw1, kw2] → list
            value = value.strip("[]")
            meta[key] = [k.strip() for k in value.split(",") if k.strip()]
        elif key in ("primary_keyword", "slug", "schema_type", "search_intent"):
            meta[key] = value
    return meta


def _slugify_fallback(title: str) -> str:
    """Generate a basic URL slug from the title as fallback."""
    slug = title.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug[:60]


def _reading_time(text: str) -> str:
    """Estimate reading time at 200 words per minute."""
    words = len(text.split())
    minutes = max(1, round(words / 200))
    return f"{minutes} min"


def _fallback_description(draft: str) -> str:
    """Extract the first meaningful words from the draft, skipping Markdown headings."""
    for line in draft.splitlines():
        stripped = line.strip().lstrip("#").strip()
        if len(stripped) > 40:
            words = stripped.split()[:20]
            return " ".join(words) + "..."
    return draft[:120] + "..."


def _smart_tags(draft: str, article: dict, interest_topics: list[str]) -> list[str]:
    """Content-aware tag selection: match topics against both title AND full draft body."""
    combined = (article.get("title", "") + " " + draft).lower()
    matched = [t for t in interest_topics if t.lower() in combined]
    # Deduplicate preserving order, cap at 6
    seen = set()
    tags = []
    for t in matched:
        if t.lower() not in seen:
            seen.add(t.lower())
            tags.append(t)
        if len(tags) >= 6:
            break
    return tags if tags else interest_topics[:3]


def _build_blog_post(draft: str, run_date: str, tags: list[str],
                     title: str, description: str, lang_code: str,
                     seo: dict) -> str:
    """Prepend rich YAML front matter to the validated draft. Does not rewrite the content."""
    slug = seo.get("slug", "")
    canonical = f"{SITE_URL.rstrip('/')}/{slug}/" if slug else ""

    front_matter: dict = {
        "title": title,
        "date": run_date,
        "author": "Mohamad",
        "lang": lang_code,
        "description": description[:160],
        "tags": tags,
        "reading_time": _reading_time(draft),
    }

    # SEO enrichment from LLM
    if slug:
        front_matter["slug"] = slug
    if canonical:
        front_matter["canonical"] = canonical
    if seo.get("keywords"):
        front_matter["keywords"] = seo["keywords"]
    if seo.get("schema_type"):
        front_matter["schema_type"] = seo["schema_type"]
    if seo.get("search_intent"):
        front_matter["search_intent"] = seo["search_intent"]
    if seo.get("internal_links"):
        front_matter["internal_links"] = seo["internal_links"]

    yaml_block = yaml.dump(front_matter, allow_unicode=True, default_flow_style=False).strip()
    return f"---\n{yaml_block}\n---\n\n{draft}"


def formatter_node(state: PipelineState) -> dict:
    """
    - title + description: generated by LLM (strong hook)
    - blog_post: rich YAML front matter + validated draft (NO LLM rewrite)
    - linkedin_post + youtube_script: generated by LLM
    - SEO metadata: slug, keywords, schema_type, search_intent
    """
    draft = state["draft"]
    run_date = state.get("run_date", "")
    article = state.get("selected_article", {})

    lang_code = state.get("output_language", "en")
    output_language = OUTPUT_LANGUAGE_LABELS.get(lang_code, "English")

    tags = _smart_tags(draft, article, INTEREST_TOPICS)

    # Fallbacks if LLM fails
    title = article.get("title", "Article")
    description = _fallback_description(draft)

    linkedin_post = youtube_script = ""
    seo_meta: dict = {}
    tokens_used = 0

    prompt_template = (PROMPTS_DIR / "formatter_social.md").read_text()
    prompt = (prompt_template
              .replace("{draft}", draft)
              .replace("{date}", run_date)
              .replace("{tags}", ", ".join(tags))
              .replace("{output_language}", output_language))

    try:
        print("[FORMATTER]  Generating title/description/SEO/social formats via LLM...")
        response = llm_client.chat.completions.create(
            model=LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=LLM_TEMPERATURE,
        )
        raw = response.choices[0].message.content.strip()
        tokens_used = response.usage.total_tokens if response.usage else 0

        title = _extract_section(raw, "TITLE") or title
        description = _extract_section(raw, "DESCRIPTION") or description
        linkedin_post = _extract_section(raw, "LINKEDIN")
        youtube_script = _extract_section(raw, "YOUTUBE")

        raw_seo = _extract_section(raw, "SEO_META")
        if raw_seo:
            seo_meta = _parse_seo_meta(raw_seo)
            if not seo_meta.get("slug"):
                seo_meta["slug"] = _slugify_fallback(title)
            print(f"[FORMATTER]  SEO → slug={seo_meta.get('slug')} | "
                  f"schema={seo_meta.get('schema_type')} | "
                  f"kw={seo_meta.get('primary_keyword')}")
        else:
            seo_meta["slug"] = _slugify_fallback(title)
            print("[FORMATTER]  SEO meta missing — slug generated from title")
    except Exception as exc:
        print(f"[FORMATTER] LLM error: {exc}")
        seo_meta["slug"] = _slugify_fallback(title)

    blog_post = _build_blog_post(draft, run_date, tags, title, description, lang_code, seo_meta)

    blog_words = len(draft.split())
    linkedin_chars = len(linkedin_post)
    yt_words = len(youtube_script.split())
    yt_seconds = round(yt_words / 150 * 60)
    read_time = _reading_time(draft)
    print(f"[FORMATTER]  Blog: {blog_words} words (~{read_time}) | "
          f"LinkedIn: {linkedin_chars} chars | YouTube: ~{yt_seconds}s script")

    msg = ACPMessage(
        sender="formatter",
        receiver="output_saver",
        msg_type="result",
        content="4 formats ready (blog + LinkedIn + YouTube + SEO meta)",
        metadata={"tokens": tokens_used, "slug": seo_meta.get("slug", "")},
    )
    return {
        "blog_post": blog_post,
        "linkedin_post": linkedin_post,
        "youtube_script": youtube_script,
        "total_tokens_used": state.get("total_tokens_used", 0) + tokens_used,
        "messages": [msg],
    }
